### ISSUE TITLE
Small bug in member section

### ISSUE THREAD

**Issue by OmPr366** [GFG-CLUB-KIIT/GFG-KIIT-website#53]
When in light mode , the following text becomes invisible because of its  white color and white background.

![image](https://user-images.githubusercontent.com/71120474/136271638-c0b37308-1f38-4916-839f-1f31ea48d4cc.png)

You can fix it by shifitng the text upwards.

**Comment by OmPr366** [comment]
Problem fixed.

![image](https://user-images.githubusercontent.com/71120474/136330974-0b431c45-4f8b-46ff-88d7-af3fe2566a56.png)


[Merge It](https://github.com/GFG-CLUB-KIIT/GFG-KIIT-website/pull/59)

**Comment by OmPr366** [comment]
Problem fixed.

![image](https://user-images.githubusercontent.com/71120474/136330974-0b431c45-4f8b-46ff-88d7-af3fe2566a56.png)


[Merge It](https://github.com/GFG-CLUB-KIIT/GFG-KIIT-website/pull/59)

**Comment by ashishmishra-bit** [comment]
This is fixed you might have the resolution problem check once.

**Comment by OmPr366** [comment]
This problem is coming  while changing resolution .
