### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by OmPr366** [GFG-CLUB-KIIT/GFG-KIIT-website#57]
While toggeling the dark mode on the color of the navbar remains white :- 

![image](https://user-images.githubusercontent.com/71120474/136325701-02190761-4ebd-4580-9920-567f53513832.png)

**Comment by OmPr366** [comment]
Is there anyone who can help in fixing this problem ?

**Comment by Palaksharma23** [comment]
@OmPr366 i can try in helping with this issue .

**Comment by OmPr366** [comment]
go ahead @Palaksharma23
